# Workflow for running locally (e.g., via https://github.com/nektos/act)
#
# Note:
# - Invoked via local-workflows.sh:
#   act --container-architecture linux/amd64 --pull="false" -P "ubuntu-latest=local/test-act" -W ./.github/workflows/act.yml

name: Act-Tests

on: [push, pull_request]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-20.04]
        #remove python version

    container:
      image: shell-scripts-dev
      options: --user=root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build -t shell-scripts-dev -f- . <Dockerfile

      - name: Run tests
        run: |
          docker run --rm --mount type=bind,source="$(pwd)",target=/home/shell-scripts shell-scripts-dev
