# Workflow for running locally (e.g., via https://github.com/nektos/act)
#
# Note:
# - Invoked via local-workflows.sh:
#   act --container-architecture linux/amd64 --pull="false" -P "ubuntu-latest=local/test-act" -W ./.github/workflows/act.yml

name: Act-Tests

## OLD [WTF? This is supposed to be local testing!]
## on:
##   push:
##     branches:
##       - main
##   pull_request:
##     branches:
##       - main

on: [push, pull_request]

jobs:
  build:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    container:
      ## OLD: image: local/test-act
      image: shell-scripts-dev
      options: --user=root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build -t shell-scripts-dev -f- . <Dockerfile

      - name: Configure Environment
        run: |
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.9/dist-packages" >> $GITHUB_ENV

      - name: Run Python Tests
        run: |
          PYTHONPATH="$(pwd):$PYTHONPATH" python3 tests/master_test.py

      - name: Run Bats-PP Alias Tests
        run: |
          PYTHONPATH="$(pwd):$PYTHONPATH" bash tests/summary_stats.bash
