# This workflow will run the Python and Bash alias tests
#
# Notes:
# - Based on tests.yml from Python mezcla package.
# - It runs with detailed debugging (i.e., DEBUG_LEVEL=5).
# - Requires special permission for Github workflows.
# - For more information see following:
#     https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#     https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# - Based initially on version from https://github.com/LimaBD/batspp.
# - Running Github Actions with Docker: https://stackoverflow.com/a/64373702
# - Docker documentation:
#   https://docs.docker.com/engine/reference/commandline/cli/
#   https://docs.docker.com/storage/bind-mounts
#

name: debug-Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      run: |
        docker build -t shell-scripts-dev -f- . <Dockerfile

    ## TEST
    - name: Configure Environment
      run: |
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.9/dist-packages" >> $GITHUB_ENV

    - name: Run tests
      run: |
        docker run --env "DEBUG_LEVEL=5" --rm --mount type=bind,source="$(pwd)",target=/home/shell-scripts shell-scripts-dev
